### ISSUE TITLE
kexec is redefined as an alias

### ISSUE THREAD

**Issue by PeterHeja** [Dbz/zsh-kubernetes#1]
I know it is rarely used, but kexec will be redefined as an alias when people use this plugin.

**Comment by Dbz** [comment]
Hey Peter, what do you mean by that?

**Comment by PeterHeja** [comment]
https://en.wikipedia.org/wiki/Kexec
kexec is the command that does this, which will be in your path - if you have it installed -, but it will be overwritten with an alias if you use this plugin.

**Comment by Dbz** [comment]
Interesting. Do you think it's worth changing the function name to `kcexec` instead?

**Comment by Dbz** [comment]
Changed to `kcexec`
